### ISSUE TITLE
Permission Error

### ISSUE THREAD

**Issue by jroberayalas** [jdb78/pytorch-forecasting#212]
- PyTorch-Forecasting version: 0.7.1
- PyTorch version: 1.7.1
- Python version: 3.8.5
- Operating System: MacOS Mojave 10.14.6

I'm currently running the code in the [tutorial](https://pytorch-forecasting.readthedocs.io/en/latest/tutorials/stallion.html) for demand forecasting. Everything runs fine except when I run the tuner code:

```
res = trainer.tuner.lr_find(
    tft,
    train_dataloader=train_dataloader,
    val_dataloaders=val_dataloader,
    max_lr=10.0,
    min_lr=1e-6,
)
```

I get a Permission Error: `PermissionError: [Errno 13] Permission denied: '/Users/lr_find_temp_model.ckpt'`.

The same occurs when trying to fit the model: `PermissionError: [Errno 13] Permission denied: '/Users/lightning_logs'`. Any guidance on how to solve this is greatly appreciated.

**Comment by jroberayalas** [comment]
I solved the issue by simply removing the code `os.chdir("../../..")` on the first cell. Is it really necessary to use this?

**Comment by jdb78** [comment]
It is absolutely not necessary - it's only task is to allow execution without having to install pytorch-forecasting explicitly.

**Comment by Jinwen321** [comment]
I also encountered this problem. Are there any solutions?

**Comment by OweN98** [comment]
`File ~/anaconda3/envs/pytorch-forecasting/lib/python3.8/site-packages/pytorch_lightning/tuner/lr_finder.py:226, in lr_find(trainer, model, min_lr, max_lr, num_training, mode, early_stop_threshold, update_attr)
    224 ckpt_path = os.path.join(trainer.default_root_dir, f".lr_find_{uuid.uuid4()}.ckpt")
    225 ckpt_path = trainer.strategy.broadcast(ckpt_path)
--> 226 trainer.save_checkpoint(ckpt_path)`
I found this information in Traceback, the `ckpt_path` will include the `default_root_dir`. In some situation, the default root can not get permission.
By adding the `default_root_dir='{YOUR PATH}'` when `trainer` is initialized, the problem is solved.
