### ISSUE TITLE
Saving/Loading Models & Training Pre-Trained models on New Data

### ISSUE THREAD

**Issue by GR1994** [jdb78/pytorch-forecasting#225]
Hi,

I'm struggling to understand how to save a model to file and load it later on, for example, I created a TFT model and trained it, now I want to save it to file to a specific output path, later on, I want to load it from that file and continue generating predictions, what methods can help me with that?

Also, assuming I have loaded a pre-trained model, is it possible to continue training it on new data? if so, how that would be done? 

Thanks in advance,
Guy

**Comment by jdb78** [comment]
Just use the `torch.load()` and `torch.save()` functions - there is a potential issue with reproducibility in the 0.7.1 in the `TimeSeriesDataSet`, which is already fixed in the master (PR #221) and will be released shortly.

Transfer learning is not trivial with time series models because they are so task specific (see also issue #198) and I am not aware of significant success stories such as in CV or NLP (but if you heard some, please let me know!). Aside, PyTorch Forecasting models can be used as regular PyTorch models (and inherit from `nn.Module`). This means you can use them as part of another model and transfer weights (and freeze) them as you wish for transfer learning. The TFT might lend itself well to transfer learning for narrow tasks because it embeds its features first. It is on the to-do list.

**Comment by GR1994** [comment]
Got it, Thank you for the quick answer!

**Comment by louisowen6** [comment]
Hi, I'm trying to load a saved model and try to retrain the model on the new data with more samples. However, when I try to do that, there's an error like this:

`IndexError: index out of range in self`

Can you guide me on how to do it in the correct way? Thanks!
