### ISSUE TITLE
Awkward concatenation logic in .predict()

### ISSUE THREAD

**Issue by geniki** [jdb78/pytorch-forecasting#275]
- PyTorch-Forecasting version: 0.8.2
- PyTorch version: 1.7.1
- Python version: 3.6
- Operating System: Linux

### Expected behavior

I executed code `some_model.predict(..., mode="prediction")`  in order to obtain predictions and expected to get result in the shape of something like `(num_examples, num_targets, decoder_length)`

### Actual behavior

However, result was in the shape of list of length `num_batches` and each element is of size `(batch_size * num_targets, decoder_length)`. A `batch_size * num_targets` dimension doesn't feel very convenient. I think it has to do with concatenation along the wrong dimension in the code line below.

### Code to reproduce the problem
The relevant line is here and any example in the docs works
```
https://github.com/jdb78/pytorch-forecasting/blob/master/pytorch_forecasting/models/base_model.py#L809
```

**Comment by huayicodes** [comment]
Also noticed this bug causes predictions to fail due to mismatches in dimensions. A temporary workaround is to format the data into dataloaders. 

However, there's another problem that might be related to this. So after I upgraded to 0.8.2 . I noticed that the prediction results are different when I pass all timeseries into a dataloader and then make predictions VS when I select a small subset or individual timeseries.

Any idea what might be going on?
