### ISSUE TITLE
Question: Understanding the X and y TimeSeriesDataSet produces

### ISSUE THREAD

**Issue by smkaropp** [jdb78/pytorch-forecasting#478]
I know this issue doesn't really comply with the draft but this isn't really about a bug, rather the methodology.

I am pretty new at time series forecasting and trying to understand encoder/decoder networks. I understand that I give a set of values for say `t-4`, `t-3`, `t-2`, `t-1` and `t` to forecast `t+1` and `t+2` but I don't understand why we also put `t+1` and `t+2` to the `X`.

For instance, in this tutorial, [https://pytorch-forecasting.readthedocs.io/en/latest/tutorials/building.html#passing-data](https://pytorch-forecasting.readthedocs.io/en/latest/tutorials/building.html#passing-data), when I also use `target_normalizer=None`, all values in `y`, `X['decoder_cont']` and `X['decoder_target']` becomes same. Why do we pass the output we aim to the network? Could you please refer me to a reading or briefly explain the rationale here?

**Comment by jdb78** [comment]
You pass the normalized target (in "decoder_cont") because in some instances it is needed for training. For instance, it is used for teacher-forcing in the autoregressive DeepAR network. In prediction mode, it is automatically overwritten. For plotting results the non-normalized target is useful ("decoder_target").
When defining the architecture, you have to make sure there is no leakage. This is easily checked by modifying the numbers in prediction mode and checking that results remain the same.

**Comment by smkaropp** [comment]
Thanks for detailed answer!
