### ISSUE TITLE
Temporal Fusion Transformer - Forecasting for longer period than training data. <question>

### ISSUE THREAD

**Issue by damianski794** [jdb78/pytorch-forecasting#505]
- PyTorch-Forecasting version: 0.8.5
- PyTorch version: 1.8.1
- Python version: 3.7.10
- Operating System: windows

Hi,
I have a dataset with 2 columns: date, price. Data is a type of time series.
Data is available for **past 250 days**. Is it possible to forecast the price for **next 365 days** with **Temporal Fusion Transformer**?

I've seen in the tutorial zone that  forecast of stallion_data was made for a significatly shorter period than length of available training data.
![image](https://user-images.githubusercontent.com/33297451/118122475-34408300-b3f3-11eb-895c-8d5097a8ab41.png)

**Comment by jdb78** [comment]
The answer is not clear cut. You can create a new dataset that is longer than the available data (where the target / unknown variables are dummies). When you use `from_dataset` to create it, ensure to pass `max_prediction_length=365`. This way, you will get your desired result. HOWEVER, I would rather use a model such as DeepAR for this because the TFT is not an autoregressive model and your use case might lead to undefined behaviour.

**Comment by damianski794** [comment]
Thanks for the answer @jdb78.
