### ISSUE TITLE
Default scalers are leaking prediction samples into train

### ISSUE THREAD

**Issue by danielgafni** [jdb78/pytorch-forecasting#751]
- PyTorch-Forecasting version: 0.9.1

### Code to reproduce the problem

```python
import numpy as np
import pandas as pd
from pytorch_forecasting import TimeSeriesDataSet

data = pd.DataFrame(
    {
        "group": np.zeros(5),
        "time_idx": np.arange(5),
        "a": np.random.rand(5),
        "target": np.random.rand(5)
    }
)

ds = TimeSeriesDataSet(
    data,
    time_idx="time_idx",
    group_ids=["group"],
    target="target",
    min_encoder_length=4,
    max_encoder_length=4,  # train on the first 4 rows
    min_prediction_length=1,
    max_prediction_length=1,  # predict the last row
    time_varying_known_reals=["a"]
)

assert ds.scalers["a"].n_samples_seen_ == 5
```

As can be seen, scalers are fitted on the whole dataframe (n_samples_seen_ = 5) and not on the first 4 rows.

**Comment by chefPony** [comment]
By default `TimeSeriesDataSet `uses `StandardScaler` that scales samples on the whole dataset, so this is just the expected behaviour. If you want to scale using only the encoder sequence you should use the `EncoderNormalizer`. Otherwise you should create two separate dataset by splitting train and test samples.
